apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-service
  template:
    metadata:
      labels:
        app: test-service
    spec:
      volumes:
      - name: config
        emptyDir: {}
      containers:
      - name: web
        image: europe-central2-docker.pkg.dev/easy-configs/docker/test-service
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /config
          name: config
      - name: git-sync
        image: openweb/git-sync
        imagePullPolicy: Always
        env:
        - name: VAR_NAME
          value: value
        - name: GIT_SYNC_REPO
          value: https://github.com/skalinets/easy-configs-config.git
        - name: GIT_SYNC_DEST
          value: /config
        - name: GIT_SYNC_BRANCH
          value: master
        - name: GIT_SYNC_REV
          value: FETCH_HEAD
        - name: GIT_SYNC_WAIT
          value: "60"
        volumeMounts:
        - mountPath: /config
          name: config
---
apiVersion: v1
kind: Service
metadata:
  name: test-service
  namespace: default
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: test-service
